In [1]:
%matplotlib inline
import numpy as np

In [2]:
a = np.arange(10, 30).reshape(4, 5)
print(a)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [3]:
red = a[0, 1:4]
yellow = a[0, 0]
green = a[0:3, 2]
blue = a[:, 1::2]
purple = a[::2, 4]

print('red:',red,'\nyellow:',yellow,'\ngreen:',green,'\nblue:\n',blue,'\npurple:',purple)

red: [11 12 13] 
yellow: 10 
green: [12 17 22] 
blue:
 [[11 13]
 [16 18]
 [21 23]
 [26 28]] 
purple: [14 24]


### Class exercise: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [4]:
cube = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)
print(cube)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [5]:
one = cube[1, 1, :]
two = cube[:, 1, 0]
three = cube[0, :, 2]

print('1:',one,'\n2:',two,'\n3:',three)

1: [12 13 14] 
2: [ 3 12 21] 
3: [2 5 8]


## Exercise numpy and csv

1. load the csv file: befkbhalderstatkode.csv into a numpy ndarray
2. How many german children were 0 years old in 2015?
3. create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data
4. create a new function like previous so that it can sum values for all ages if age is not provided to the function
5. further add functionality to sum values if citizenship or area was not provided to function.
6. create a new function that can also give average values for each year if year whas not provided.
7. create a function, that given year and nationality can return which area had the most of these nationals by that year. Test it by finding out which area had the most Moroccan people in both 1992 and 2015
8. Find the Area(s) where fewest foreingers lived in Copenhagen in 1992 and 2015 respectively
9. Find out what age most French people have in 2015

In [6]:
array = np.genfromtxt(('../../../data/befkbhalderstatkode.csv'), delimiter=',', dtype=np.uint, skip_header=1)
print(array)

[[2015    1    0 5100  614]
 [2015    1    0 5104    2]
 [2015    1    0 5106    1]
 ...
 [1992   99   89 5100    1]
 [1992   99   90 5180    1]
 [1992   99   93 5100    1]]


In [14]:
mask = (array[:,0] == 2015) & (array[:,3] == 5180) & (array[:,2] == 0)
np.sum(array[mask][:,4])
amount = np.sum(array[mask][:,4])
print('Amount of German children age 0 in 2015: ' + str(amount))

Amount of German children age 0 in 2015: 35


In [16]:
def getPopulation(year, cityArea, age, stateCode):
    custom_mask = (array[:,0] == year) & (array[:,1] == cityArea) & (array[:,2] == age) & (array[:,3] == stateCode)
    return np.sum(array[custom_mask][:,4])

In [17]:
print(getPopulation(2015, 1, 0, 5100))

614
